### ISSUE TITLE
Google's S2 Repo

### ISSUE THREAD

**Issue by SymbolixAU** [spatstat/s2#7]
I *think* Google have updated / released their s2 repo and are now maintaining it

- Blog post announcing it: https://opensource.googleblog.com/2017/12/announcing-s2-library-geometry-on-sphere.html
- homepage: https://opensource.googleblog.com/2017/12/announcing-s2-library-geometry-on-sphere.html
- source code: https://github.com/google/s2geometry

Is it worth moving to this one, rather than the fork of the older one that's no longer maintained?

**Comment by rubak** [comment]
Thanks for the heads up. That will definitely be the way to go in future versions.

**Comment by SymbolixAU** [comment]
No worries. I'm going to have a poke around to see if I can get it going too. Will let you know if I get anywhere.

**Comment by rubak** [comment]
Maybe we should discuss the strategy together @SymbolixAU and figure out if we can combine our efforts? It would be really cool to figure out if we can port this major upgrade to R. How much time are you willing to invest in this? Is it an important project that you can see the immediate benefit from professionally or just a fun hobby project?

**Comment by SymbolixAU** [comment]
I think it will link nicely to my [googleway](https://github.com/SymbolixAU/googleway) (CRAN) and [googlePolylines](https://github.com/SymbolixAU/googlePolylines) (DEV) packages. I use encoded polylines a lot for plotting, so adding spatial-calculation capabilities to them will be a bonus.

I won't have any meaningful time to spend on this before 2018, but after I should be able to spend a bit of time on it. 

In terms of importance; it's not critical for me or my work, so at the moment it's more of a hobby that I'm doing in my spare time.

**Comment by rubak** [comment]
I was just finishing some testing on the library as you wrote this. I'm able to compile the library with the R toolchain now, but there are some drawbacks to consider before spending too much time on this:

- It depends on [glog](https://github.com/google/glog/) and [gflags](https://github.com/gflags/gflags/) being installed with headers on the path, which is easy on my linux box, but is it possible on OSX and Windows and more importantly is it possible on CRAN?

- The official documentation says Windows isn't supported at the moment. Does it compile on Windows? (If not, it is a bit of a shame since the old library worked on Windows.)

**Comment by SymbolixAU** [comment]
I too was looking into the 'glog' component to see if it had been done before - https://chat.stackoverflow.com/transcript/message/40390556#40390556

But, I'm not completely au-fait with C++, libraries, linking, headers etc, so I'm learning as I go..

**Comment by SymbolixAU** [comment]
I've had a play to try to get it working. I started small by loading in the minimal amount .cpp/.h files as I could that got it compiling and running simple functions. I then added more & more, and at the same time removing all `glog` library calls. It was going well, but I'm now having issues with ssl that seem to be [similar to your other issue](https://github.com/spatstat/s2/issues/2). And I have no idea how to solve it at the moment.

**Comment by rubak** [comment]
I didn't try the new code with OpenSSL 1.1 yet, but if the issue is similar we can probably fix it. Would it be possible for you to use the old OpenSSL 1.0 on your machine and see if it works with that version? As mentioned before I have a fully functioning version on my machine which depends on glog and gflags. I have tested the spherical index etc. and it is lightning fast. However, I'm running the old OpenSSL version and didn't test with a newer one yet:

```
$ openssl version
OpenSSL 1.0.1f 6 Jan 2014
```
